[package]
name = "logic-eval-util"
version = "0.1.2"
edition = "2024"
rust-version = "1.89"
description = "utility for logic-eval"
readme = "README.md"
repository = "https://github.com/ecoricemon/logic-eval"
license = "Apache-2.0 OR MIT"

[lib]
crate-type = ["rlib"]

[dependencies]
any-intern = { workspace = true }
smallvec = { workspace = true }
fxhash = { workspace = true }
