[package]
name = "logic-eval-home"
version = "0.0.0"
edition = "2024"
rust-version = "1.85"
repository = "https://github.com/ecoricemon/logic-eval"
license = "Apache-2.0 OR MIT"

[lib]
crate-type = ["rlib"]

[workspace]
members = ["crates/*"]

[workspace.dependencies]
indexmap = { version = "2.12.0" }
ahash = { version = "0.8.12" }
smallvec = { version = "1.15.1" }
