[package]
name = "logic-eval"
version = "0.2.0"
edition = "2024"
rust-version = "1.89"
description = "A simple logic evaluator"
readme = "README.md" 
repository = "https://github.com/ecoricemon/logic-eval"
license = "Apache-2.0 OR MIT"
keywords = ["logic"]

[lib]
crate-type = ["rlib"]

[dependencies]
any-intern = { workspace = true }
logic-eval-util = { workspace = true }
indexmap = { workspace = true }
fxhash = { workspace = true }
