[package]
name = "logic-eval"
version = "0.1.4"
edition = "2021"
rust-version = "1.65"
description = "A simple logic evaluator"
readme = "README.md"
repository = "https://github.com/ecoricemon/logic-eval"
license = "Apache-2.0 OR MIT"
keywords = ["logic"]

[lib]
crate-type = ["rlib"]

[dependencies]
any-intern = { workspace = true }
logic-eval-util = { workspace = true }
indexmap = { workspace = true }
fxhash = { workspace = true }
